site_name: Spring AI Learning
theme:
  name: material
  features:
    - navigation.expand
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    admonition:
      info: fontawesome/solid/circle-info
    repo: fontawesome/brands/github
  custom_dir: doc_themes

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - 'Overview': overview.md
  - 'AI Concepts': aiconcepts.md
  - 'Getting Started': getstarted.md
  - 'Spring AI API':
      - 'Chat Client': ai/chat-client.md
      - 'Chat model API': 
          - 'Overview': ai/chat-model.md
          - 'Azure OpenAI': ai/chat/azure.md
          - 'AWS': ai/chat/aws.md
      - 'Embedding Model API': 
          - 'Overview': ai/embedd-model.md
          - 'Azure OpenAI': ai/embed/azure.md
          - 'AWS': ai/embed/aws.md
      - 'Vector Database': 
          - 'Overview': ai/vectordb.md
          - 'SAP HANA': ai/vectordb/hana.md
          - 'Neo4j': ai/vectordb/neo4j.md
      - 'Multimodality': ai/multimodality.md
      - 'Prompts': ai/prompt.md


repo_url: https://github.com/GAmaranathaReddy/spring-genai
repo_name: G AmaranathaReddy/spring-genai
edit_uri: /edit/main/docs/

site_url: !!python/object/apply:os.getenv ['GITHUB_PAGES_URL', '']

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: custom
      timezone: UTC
      custom_format: '%Y-%m-%d %H:%M:%S %Z'
      fallback_to_build_date: true
  - git-authors
  - tags:
      tags_file: tags.md

watch:
  - 'doc_themes'
